### ISSUE TITLE
Random s3 bucket names

### ISSUE THREAD

**Issue by skovhus** [mads-hartmann/hatch#20]
Consider if we should just create random s3 bucket names instead of make this step configurable. As bucket names are global there is a high chance of collisions... And if you want a fixed name you might have a domain.

Similar approach as `now`.

Thoughts @mads-hartmann ?

**Comment by mads-hartmann** [comment]
Yeah, I think that'd be nice 👍 Then we only configure route53 and cloudfront if the user has specified a domain name.

**Comment by skovhus** [comment]
Not sure if we should even allow the `name` parameter in the config file.

**Comment by mads-hartmann** [comment]
Let's keep it for a bit, I think there might still be some valid use cases for it :)
